### PR TITLE
Some whitespace and syntax cleanups

### PR DESCRIPTION
**Pull request by johnf**
Tidy up some whitespace irregularities and make some syntax consistent. Some basic linting really.

### CODE REVIEW

**Comment by itrestian** [comment]
You might want to pull first and send the pull request, we have made some changes.

**Comment by johnf** [comment]
rebased

**Comment by itrestian** [comment]
Also, can you confirm that we can use, modify, copy, and redistribute this PR? Thanks!

**Comment by johnf** [comment]
Absolutely! :)

**Pull request merged**
