### PR TITLE
Replace jsbn with minimal internal BigInteger implementation

### PR DESCRIPTION
**Pull request by mhart**
Extracted only the jsbn removal from #262

This PR removes the external jsbn dependency, replacing all references with the minimal subset needed for this project.

All public methods from the original have been removed except the following:
  - new BigInteger(a, b) (only radix 2, 4, 8, 16 and 32 supported)
  - toString (only radix 2, 4, 8, 16 and 32 supported)
  - negate
  - abs
  - compareTo
  - bitLength
  - mod
  - equals
  - add
  - subtract
  - multiply
  - divide
  - modPow

### CODE REVIEW

**Comment by mhart** [comment]
Will rebase this now that #281 has been merged

**Comment by itrestian** [comment]
Sounds good.

**Comment by mhart** [comment]
Done 👍

**Comment by mhart** [comment]
Will rebase this

**Comment by mhart** [comment]
Done 👍

**Comment by itrestian** [comment]
Discussed this internally and we would need to add attribution of the big integer library in the notice file.

**Comment by mhart** [comment]
@itrestian sure, go for it

**Pull request merged**
