### PR TITLE
updated readme 

### PR DESCRIPTION
**Pull request by sarah-pixvana**
more details outlined on password reset and integrating with federated identity

### CODE REVIEW

**Comment by itrestian** [comment]
Looks good. Just change

 +If you would like the user the input the confirmation code on another page, you can make inputVerificationCode call a no-op 

to

 +If you would like the user to input the confirmation code on another page, you can make inputVerificationCode call a no-op

**Comment by sarah-pixvana** [comment]
Ok done!

**Comment by itrestian** [comment]
Can you confirm that we can use, modify, copy, and redistribute this PR? Thanks!

**Comment by sarah-pixvana** [comment]
Yes

**Pull request merged**
