### PR TITLE
Remove aws-sdk dependency

### PR DESCRIPTION
**Pull request by jogold**
This PR completely removes the `aws-sdk` dependency.
* `util` is removed by using `buffer` and `crypto-browserify` directly (same versions as those used by the `aws-sdk`)
* `CognitoIdentityServiceProvider` is replaced by a `fetch` client (with a polyfill for older browers using `whatwg-fetch`)

The idea behind this PR is that this library makes only unauthenticated calls to AWS, but due to the structure of the `aws-sdk`, a lot gets imported when bundling, see below (using `webpack-bundle-analyzer`):

image

The `dist` files are not included in this PR but here is an idea of the sizes:
* Before: amazon-cognito-identity.min.js 43.6 KB (10 KB gz) + aws-cognito-sdk.min.js 253 KB (65.8 KB gz) = 296.6 KB (75.8 KB gz)
* After: amazon-cognito-identity.min.js 98.9 KB (26.9 KB gz)

I would be happy to discuss this proposal with the people from AWS before going further with changes (update doc, webpack config, build, ...)

**Note**: Because the [JSON schema of the API](https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.normal.json) is not used to parse/format the http response, the response objects (in js) are slightly different, e.g. when using `ListDevices` dates are returned as timestamps. This is a breaking change.

---
This change is [Reviewable](https://reviewable.io/reviews/aws/amazon-cognito-identity-js/473)

### CODE REVIEW

**Comment by GiuseppeCiccone** [comment]
It would be useful to reduce amazon-cognito-identity-js size.
+1

**Comment by chad-codes** [comment]
@itrestian, do you know if this is good to be merged? aws-sdk is the largest dependency in my project currently due to this. Looks like a worthwhile change before it gets outdated.

**Comment by itrestian** [comment]
Just wondering if this would work for Node and React (now) as well?

**Comment by jogold** [comment]
Hi @itrestian,

I just rebased and will analyze your question. But is there interest in this PR? With or without polyfills for Promise and Fetch? What about the fact that the JSON schema of the API is not taken into account anymore?

**Comment by itrestian** [comment]
Sure, I definitely would think some people would use it cause I guess it would slim down the bundle? Maybe create a separate branch for this or a separate repo and we can link it on the main page of the repo?

**Comment by arabold** [comment]
I would love to see this merged as we're using `amazon-cognito-identity-js` for a React universal app with both server- and client-side rendering. The `aws-sdk` is a huge beast and not straight forward to get rid of or replace client-side due to this dependency. Removing the dependency would simplify using `amazon-cognito-identity-js` in scenarios like this in my opinion. Why wouldn't you want to have this in the master branch and main library?

**Comment by itrestian** [comment]
That's what I think as well, that it is useful for users that don't want to bring in the aws sdk and want to keep the bundle size small. My comment was mostly related to if this would work in node or react.

**Comment by jogold** [comment]
Hi @itrestian,

I just rebased and updated the PR.

It should work in node (using a fetch polyfill) or react.

Changes in `dist/` are not included in the PR (rebuild of `amazon-cognito-identity` and delete `aws-cognito-sdk`)

**Comment by itrestian** [comment]
Thanks! I will look into merging this after New Years after we consult with dependent teams.

**Comment by itrestian** [comment]
Discussed this internally. On the long term, we plan to eventually merge this library into aws-amplify https://github.com/aws/aws-amplify . I cannot comment on a timeline for that. 

On the short term, we tested the pull request but there are issues on metric population because of how the user agent is set in the main aws sdk.

**Comment by jogold** [comment]
Hi @itrestian,

Thanks for the feedback. What do you mean with issues on metric population? Can this be fixed in this PR?

**Comment by aloukissas** [comment]
Given the recent breakage /w aws-sdk #646, this becomes an even more welcome PR.

**Comment by MatteCarra** [comment]
@aloukissas +1

**Comment by itrestian** [comment]
I meant these lines that were removed that set the userAgent. Internal metrics are based on those, wasn't sure why they were removed.

```
 const libraryVersion = '1.0';
 const libraryName = 'aws-amplify';
 const originalUserAgent = AWS.util.userAgent;
 if (originalUserAgent) {
   AWS.util.userAgent = function newUserAgent() {
     return `${libraryName}/${libraryVersion} ${originalUserAgent()}`;
   };
 } else {
   const previousUserAgent = AWS.config.customUserAgent || '';
   AWS.config.update({ customUserAgent: `${libraryName}/${libraryVersion} ${previousUserAgent}` });
 }
```

**Comment by jogold** [comment]
Thoses lines were removed because for me it didn't make sense to use something like `aws-sdk-js/2.96.0` in the user agent string when the dependency is gone...  I can add this back or maybe something else that makes more sense?

**Comment by itrestian** [comment]
Thanks for your work! We have merged your version into aws-amplify as can be seen here since it made sense to keep the dependencies of this library at a minimum. 

https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js

Overall, going forward, the usage for this library won't change. You will still be able to install it with npm and have the same functioning and you will get the amplify higher level abstractions as well.

**Comment by jogold** [comment]
For those interested: I forked this repo and **merged this PR** in a **new repo called [`cognitauth`](https://github.com/goldwasserexchange/cognitauth)**. 

It is published on `npm` as [`cognitauth`](https://www.npmjs.com/package/cognitauth).

https://github.com/goldwasserexchange/cognitauth
https://www.npmjs.com/package/cognitauth

**Comment by MatteCarra** [comment]
Thank you very mucy!

**Comment by itrestian** [comment]
Your pull request has been published on npm as v2.0.0 of this library. Have a look at: https://www.npmjs.com/package/amazon-cognito-identity-js

Note that we will stop publishing updates in this repo and this library will be further maintained through the AWS-Amplify repo located here: https://github.com/aws/aws-amplify/tree/master/packages

**Pull request closed without merging**
