### PR TITLE
Further Improvements on CognitoUser TypeScript definition

### PR DESCRIPTION
**Pull request by thchia**
Also amended CognitoUser.getAttributeVerificationCode to return callback.inputVerificationCode if it is a function, otherwise return callback.onSuccess

### CODE REVIEW

**Comment by itrestian** [comment]
Can you remove the dist files from the request?

**Comment by thchia** [comment]
Is this ok? I went ahead and deleted the files, since they will be generated in the build anyway. Or would you rather I submit a new PR without the files at all? Thanks

**Comment by itrestian** [comment]
I meant remove them from the pull request. I guess it would be good to generate a PR without the dist files.

**Comment by thchia** [comment]
Ok, done.

**Pull request merged**
