### PR TITLE
Add keys

### PR DESCRIPTION
**Pull request by SteveALee**
I found the api requires placeholder keys unless unauthorised user access is enabled.

### CODE REVIEW

**Comment by itrestian** [comment]
Hi Steve,

Maybe make it clear that you retrieve credentials either through the code above the dummy one or you put dummy credentials?

Ionut.

**Comment by SteveALee** [comment]
I don't quite follow.

I found i had to add the dummy credentials to the example to make it work. Unless unauthorised access was enabled (which I did not want)

What code above do you refer to?

**Comment by itrestian** [comment]
Basically both 
-   AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'}) 
  and 
    AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
       IdentityPoolId: '...' // your identity pool id here
   });

are ways to set AWS credentials. If you use the first way you won't need to do the 2nd.

The first one works because the particular API calls in question don't require credentials but the SDK actually complains if the object is null. The 2nd one just gets the credentials.

Ionut.

**Comment by SteveALee** [comment]
I prefer the second as it it doesn't have the _hacky_ values :)
Will give it a go.

**Comment by SteveALee** [comment]
So I found the hacky `AWSCognito.config.update` version can be used on it's own, otherwise need both or else get `AWS add user fail Missing credentials in config` with just the `AWSCognito.config.credentials`

**Comment by itrestian** [comment]
Yes, that's what I meant, either the hacky credentials or both the AWS.config and AWSCognito.config to be set.

**Comment by SteveALee** [comment]
:) I think I found on way home in train it also throws an exception when no
connectivity :( Will investigate

Steve Lee
OpenDirective http://opendirective.com

**Comment by SteveALee** [comment]
Skip that comment about disconnected errors - I had broken code

**Pull request merged**
