### PR TITLE
Replace sjcl with corresponding methods from aws-sdk

### PR DESCRIPTION
**Pull request by mhart**
Extracted only the sjcl removal (and cleanups / de-duplication) from #262

This PR removes the external sjcl dependency, replacing all references with corresponding methods from the `aws-sdk` which includes much of the needed functionality already (in `aws-cognito-sdk.min.js`)

### CODE REVIEW

**Comment by borisirota** [comment]
@mhart @itrestian great PR ! one issue though:

replacing
`import CognitoIdentityServiceProvider from 'aws-sdk/clients/cognitoidentityserviceprovider';`
with
`import { CognitoIdentityServiceProvider } from 'aws-sdk';`
and adding
`import { util } from 'aws-sdk';`
instead of
`import * as sjcl from 'sjcl';`

makes the whole aws-sdk to be included in the final bundle instead of only the core functionality with the relevant clients for users using this lib through `webpack` and using the `aws-sdk` externally with additional clients (s3, etc.).

Include all the aws js clients (almost 100) instead of only few which are really being used is a big overhead.

I think it should be:
`import CognitoIdentityServiceProvider from 'aws-sdk/clients/cognitoidentityserviceprovider';`
and 
`import { util } from 'aws-sdk/global'; // I didn't try it yet`

Thanks

**Comment by mhart** [comment]
@borisirota hmmm, I'm never a fan of that style of import – it gives any consuming code far too much knowledge of the internal file structure of the `aws-sdk` module.

If the internal file structure of the module changed, then you'd have to change all of your source code – so it's a very brittle solution. (also, it's not very Node-like)

It seems to me like it's a webpack config issue – is there not some way to specify in your webpack config to only use those particular paths? At least that way if the internal structure did change, you'd only need to update one file (your webpack config file)

**Comment by mhart** [comment]
I wonder if you could do it with [aliases](https://webpack.github.io/docs/configuration.html#resolve-alias):

```js
resolve: {
  alias: {
    'aws-sdk$': '/my/bundled/aws-sdk.js'
  }
}
```
Where `/my/bundled/aws-sdk.js` looks like:

```js
export { default as CognitoIdentityServiceProvider } from 'aws-sdk/clients/cognitoidentityserviceprovider'
export { util } from 'aws-sdk/global'
```
(or something like that – haven't tested)

That way you could use `import <whatever> from 'aws-sdk'` wherever you liked, but still have control over what was actually bundled, all in one central place.

**Comment by mhart** [comment]
The other, far better option, IMO – is just to make `aws-sdk` external (similar to this repo's webpack config) – and then you can [configure it with whatever services you want](https://sdk.amazonaws.com/builder/js/), and serve it up from a CDN – instead of needing to bundle it in with all of your app source every time your code changes.

**Comment by borisirota** [comment]
@mhart The thing that bothers you is that its "internal" implementation. In general I agree with you but in this case I think that this is a matter of perspective. They could have publish individual services to `npm` and then it was valid from your point of view but instead of adding complexity to their build process, the interface is accessing to the `aws-sdk/clients/*` path (check [this PR](https://github.com/aws/aws-sdk-js/pull/1123)).

This library already supports optimized bundle size (added in [this PR](https://github.com/aws/amazon-cognito-identity-js/pull/140)) and IMO I don't see a reason to break it.

I guess that manually configuring services can work for some but in my use case it breaks the automatic workflow and versioning and takes me out of the scope of `npm`. In addition, its possible to serve it within vendors bundle or as individual script while keeping the build inside the world of webpack.

You proposed a valid solution with the additional AWS entry but for me it seems redundant because I see it as a patch. If the internal implementation of `aws-sdk` will really change, it means that all the users of this library will have to change their configuration. The alternative is to update this library and then users will just update the version => the regular workflow with `npm` modules.

A real solution as I see it will be when `aws-sdk` will be written with `ES2015 modules` and then the style of imports in this PR + tree shaking with `webpack 2` or `rollup` will do the job.
So meanwhile why not using the current interface for consuming individual clients ?

IMHO, in this case, every solution which doesn't support optimized bundle size out of the box is an overkill. A user wants to use external library as is, without adding wrapper\configuration if there is no special need for that.

Thanks for this PR !

@itrestian your thoughts ?

**Comment by mhart** [comment]
@borisirota – good points. I still feel it's hacky to be "reaching in" to the module – but if AWS are officially supporting it, then I agree it's less risky.

I'll create a PR 👍

**Comment by itrestian** [comment]
I think consuming individual clients should be fine. I don't see this changing in the near future. And if it does, I can discuss with the main AWS SDK team about the changes. 

Thanks everyone!

**Comment by mhart** [comment]
@borisirota @itrestian have given it a shot here: https://github.com/aws/amazon-cognito-identity-js/pull/289

**Pull request merged**
