### PR TITLE
Add ability to forget any remembered device

### PR DESCRIPTION
**Pull request by jogold**

### CODE REVIEW

**Comment by itrestian** [comment]
Thing is, we should find a way to keep the existing behaviour because current users of forgetDevice will have to change their code if we add extra parameters.

**Comment by jogold** [comment]
Updated PR with commit to maintain original method signature.

**Comment by itrestian** [comment]
I think forgetSepcificDevice is a misspell and can you solve the conflicts with your old PR?

**Comment by jogold** [comment]
Updated PR with commits to fix typo and resolve conflicts.

**Pull request merged**
