### PR TITLE
ES Modules build

### PR DESCRIPTION
**Pull request by jogold**
* Adds ES Modules build (scripts and babel configuration)
* Adds module and jsnext:main fields in package.json
* Changes main field in package.json

---
This change is [Reviewable](https://reviewable.io/reviews/aws/amazon-cognito-identity-js/294)

### CODE REVIEW

**Comment by jogold** [comment]
Rebased

**Comment by jogold** [comment]
Removed dist files from PR.

**Comment by itrestian** [comment]
Is this change backwards compatible? Meaning the dist files for script usage will still be generated?

**Comment by jogold** [comment]
Yes, it is backwards compatible. 

Running `npm run build` will create the following:
* `lib` folder with CommonJS module
* `es` folder with ES module
*  `amazon-cognito-identity.js` and `amazon-cognito-identity.min.js` in the `dist` folder (like before)

The empty `.npmignore` ensures the new folders will be published to npm.

This also solves #315 for React/Webpack projects because the `main` field of `package.json` points to a non-minified version.

**Comment by Pwntus** [comment]
Still crashes.
Installed using `npm install aws/amazon-cognito-identity-js --save` so it should contain latest commits, right?
**Edit:** I can confirm that I've got the latest code.

I should mention that I'm writing a local NPM module that imports `amazon-cognito-identity-js`, and is then imported in my main `Vue.js` application, all using Webpack.

**Edit 2:** I ran `npm install`, `npm run build` inside the `amazon-cognito-identity-js` package and got it working. Sorry for appearing confused, but is this something that would already be done when added to the NPM registry?

**Comment by jogold** [comment]
The package has not been updated yet on NPM (still v1.16.0), so the latest commits are not included yet. Once it is updated, it should be fine.

**Pull request merged**
