### PR TITLE
Update to use aws/aws-sdk-js#1123 explicit webpack support.

### PR DESCRIPTION
**Pull request by simonbuchan**
aws/aws-sdk-js#1123 just merged and published version 2.6.0 adding native webpack support, which means we can simplify our suggested webpack setup.
- Update README.md to use new aws-sdk webpack support.
- Simplify NPM install by making the dependencies direct rather than peer dependencies.
  
  This is apparently OK for aws-sdk to do, so we should be able to may as well make it nicer
  for the end-user.
- Remove old grunt build and deps.

The webpack setup docs could later be updated to talk about optimising bundle size, essentially, never `require('aws-sdk')` / `import 'aws-sdk'`, always use `aws-sdk/global` or `aws-sdk/clients/SERVICE`:

``` js
var AWS = require('aws-sdk');
var S3 = AWS.S3;
// or
import AWS, { S3 } from 'aws-sdk';

AWS.config.region = 'us-west-1';
var s3 = new S3();
```

should instead be:

``` js
var AWS = require('aws-sdk/global');
var S3 = require('aws-sdk/clients/s3');
// or
import AWS from 'aws-sdk/global';
import S3 from 'aws-sdk/clients/s3';
```

But previous usage would still work as is so long as you update the `aws-sdk` you build your bundle from so the dist update for this should also update the `aws-cognito-sdk.min.js` build to be from 2.6.0

### CODE REVIEW

**Comment by itrestian** [comment]
So should we hold off on the merge for now or is it ok?

**Comment by simonbuchan** [comment]
Sorry, I was still a bit unclear! Just got a reply for the import issue, but that is just for the suggested usage doc update.
Otherwise I think this is good.
The convention I've seen is to have "WIP" in title until the submitter thinks it's ready

**Comment by simonbuchan** [comment]
@itrestian See edits to description, in particular this will require updating `aws-cognito-sdk.min.js` for script file users.

**Comment by borisirota** [comment]
@itrestian Hi, any reason it isn't being merged ?

**Comment by itrestian** [comment]
No reason! We will merge it but I need to do the things Simon mentioned: build aws-cognito-sdk.min.js from aws-sdk 2.6.0. And check if everything works correctly.

**Comment by borisirota** [comment]
Great Thanks 👍

**Comment by itrestian** [comment]
Can you confirm that we can use, modify, copy, and redistribute this PR? Thanks!

**Comment by simonbuchan** [comment]
You can use, modify, copy, and redistribute this PR.

**Comment by simonbuchan** [comment]
@itrestian Ping?

**Comment by itrestian** [comment]
Yes, just started working on this :).

**Comment by itrestian** [comment]
Hi Simon,

Everything works great for me. I updated aws-cognito-sdk.min.js from aws-sdk v2.6.4 and it seems to be working. I will merge ASAP!

Thanks a lot!

**Comment by itrestian** [comment]
Merged and updated dist files.

**Pull request merged**
