### PR TITLE
Fix Typings

### LINKED ISSUE #536: 1.20.0 breaks TypeScript build
There are some erroneous typings:

```
ERROR in [at-loader] ./node_modules/amazon-cognito-identity-js/index.d.ts:80:16 
    TS7010: 'getMFAOptions', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [at-loader] ./node_modules/amazon-cognito-identity-js/index.d.ts:147:36 
    TS7031: Binding element 'string' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/amazon-cognito-identity-js/index.d.ts:154:32 
    TS7031: Binding element 'string' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/amazon-cognito-identity-js/index.d.ts:161:37 
    TS7031: Binding element 'string' implicitly has an 'any' type.
```

PR #535

### PR DESCRIPTION
**Pull request by thchia**
Fixes #536

### CODE REVIEW

**Comment by thchia** [comment]
Actually, I think there are more fixes - I hit the ones that caused my build to fail but I'm going through in a bit more detail now.

**Comment by chrispaynter** [comment]
Hey @itrestian, will this fix be released as a patch to NPM in the near future? As it stands, it completely breaks typescript compilation. I've gotten around this by manually applying the 3 changes, but will be good to see it released soon :)

**Comment by itrestian** [comment]
Just did!

**Comment by chrispaynter** [comment]
Legend, thank you for being so quick @itrestian we all appreciate it!

**Pull request merged**
