### PR TITLE
Add SDK import docs

### PR DESCRIPTION
**Pull request by cmoel**
Adds clarification to README for importing library when using webpack with the `exports-loader`.

### CODE REVIEW

**Comment by itrestian** [comment]
Can you confirm that we can use, modify, copy, and redistribute this PR? Thank you!

**Comment by simonbuchan** [comment]
I don't get it? `exports-loader` changes the export value of a module to the var you provide, you can require / import that value as any name you want

**Comment by simonbuchan** [comment]
Now that I'm not on a phone:

`loader: 'exports?AWSCognito'` means that the file has `module.exports = AWSCognito;` added to the end before being wrapped in a module function, for exposition something like this:

```
// bundle.js
// ...
/* aws-sdk */ 123: function (module, exports, require) { // for exposition
// original file content, after webpack loaders and rewriting requires:
var AWSCognito = require(/* ./core */ 124);
// ...

// added by exports-loader?AWSCognito
module.exports = AWSCognito;
},
// more modules...
```

So the export name depends on the definition content, not the way you use it. Regardless of if you are using the npm `aws-sdk`, `aws-sdk.2.5.3.min.js`, `./my-custom-aws-sdk-bundle.js`, or `amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js` you can use them all the same way:

```
// var names are whatever you like (but should probably be AWS)
var foo = require('aws-sdk');
// if this resolves to the same module as 'aws-sdk', say due to resolve.alias
// then foo === bar
var bar = require('./my-custom-aws-sdk-bundle');

foo.config.credentials = ...;
var s3 = new foo.S3();
var ec2 = new bar.EC2();
```

**Comment by cmoel** [comment]
@itrestian Yes, you can use, modify, copy, and redistribute this PR.

@simonbuchan I think I understand the confusion. My goal was to clarify how to use the `exports-loader` in an application using either library, not differentiate between the two libraries. I thought adding this kind of clarification went well with the feel of this section of the README because it's very step-by-step and this step seemed to be missing. How do you recommend I change the language to better fit with the rest of the README?

**Comment by simonbuchan** [comment]
Ah, so you meant something like "**regardless** of which library you used in your webpack config"?

I would probably phrase this the other way around, and say something along the lines of 

> the examples are written as if you had used `var AWSCognito = require('aws-sdk');`, so that they match loose script usage, but you can use any name, for example use an existing `AWS` import.

Needs more copy-editing, and should be a matching comment on the loose script setup side to say something about what names the two aws-sdk's introduce.

Maybe add something about adding `var AWSCognito = AWS;` between the `aws-sdk.js` and the `amazon-cognito-identity.min.js` scripts to skip having to use `aws-cognito-sdk.js,` but really the library should only look for `AWSCognito` first and fall back to `AWS` if it's not defined....

**Comment by itrestian** [comment]
I think it would make sense to make the distinction as Simon suggested since we are not restricting to the use of AWSCognito but rather the examples are written in that way.

**Comment by simonbuchan** [comment]
Maybe should close this now as with #140 we don't have webpack setup docs talking about the cognito build any more since it should "Just Work™️" with optimal size if you only use `aws-sdk/global` and `aws-sdk/clients/*`.

**Comment by itrestian** [comment]
Sounds good. Just closed.

**Pull request closed without merging**
