### PR TITLE
Modernize Javascript, tooling, UMD build (eg Webpack).

### LINKED ISSUE #48: Webpack
How can I use this with webpack? Tried logging in a user but it seems that amazon-cognito-identity can't find jsbn despite it being imported ahead of it. 

amazon-cognito-identity.min.js:19 Uncaught ReferenceError: BigInteger is not defined

It seems that amazon-cognito-identity is being loaded before jsbn, is there a way to reverse the order?

### PR DESCRIPTION
**Pull request by simonbuchan**
Fixes #48.

Use modern tooling while maintaining compatibility:
- Add npm scripts to run local dev tool packages: eg `npm run build`
- linting with ESLint, using the most popular preset `airbnb-base` (i.e. no react) as much as possible
- build bundle with `webpack` as UMD
- transpile with `babel`, using `es2015` preset
- docs are still jsdoc :)

Linting now checks jsdocs aggressively, so I fiiled them out (double-checking I got these right would help!)

`airbnb-base` ruleset is fairly aggressive, in particular it rejects `if { ...; return x; } else { ... }`, so some re-ordering was needed (done with IntelliJ intentions to avoid typos)

Webpack configured to build a UMD bundle now, so it is usable directly from bundlers.
- In node / requirejs / amd usage, uses `require("aws-sdk")`
- In `<script>` / concat usage, still uses global `AWSCognito` for compat.
- `jsbn` (for `BigInteger`) and `sjcl` deps are npm peer dependencies excluded from the bundle to respect licensing concerns by AWS.

With babel now tranpiling, use es2015 modules and classes for source.

I would like to get some node tests in there with `ava`, but it would require factoring out the browser dependencies, mostly the `localStorage` stuff if the `aws-sdk` import can be shimmed.

Example webpack client usage is mostly working around npm `aws-sdk` not being UMD (?):

```
// aws-sdk's `browser` package prop pointing at `lib/browser.js` is picked up by default,
// but doesn't webpack correctly due to still having dynamic `require()` calls that match
// server-only code.
// Simple fix is to point it at the bundle, a better fix would be disabling the automatic
// resolve contexts: https://webpack.github.io/docs/configuration.html#automatically-created-contexts-defaults-module-xxxcontextxxx
// but then you need to include the services yourself, see aws-sdk/dist-tools/service-collector

var AWS_SDK_MAIN = require.resolve('aws-sdk/dist/aws-sdk.min.js');

module.exports = {
  // entry, outputs as usual...
  resolve: {
    alias: {
      'aws-sdk$': AWS_SDK_MAIN
    }
  },
  module: {
    noParse: /aws-sdk/, // shut up warnings about it being already built
    loaders: [
      { test: AWS_SDK_MAIN, loader: 'exports?AWS' },
      // ... your loaders, eg js -> babel
    ]
  }
};
```

### CODE REVIEW

**Comment by itrestian** [comment]
Can you confirm that we can use, modify, copy, and redistribute this PR? Thank you!

**Comment by simonbuchan** [comment]
Implicit under 3.1 in ASL, but yes, of course :)

**Comment by simonbuchan** [comment]
Rebased over 960bc52d8764471001e496c48353ca270be4bdef since it just rebuilt the bundle.

**Comment by itrestian** [comment]
Worked for me. Any reason why you commented out the deviceStuff lines in CognitoUser?

**Comment by simonbuchan** [comment]
> Worked for me. Any reason why you commented out the deviceStuff lines in CognitoUser?

eslint errors on unused definitions :)

**Comment by jeffski** [comment]
I can't get this to work, what am I doing wrong?

I have npm installed aws-sdk, jsbn, moment, sjcl and amazon-cognito-identity-js (via github).

I have added the suggested AWS_SDK_MAIN configuration from above to my webpack config file.

In my script I am using `import AWSCognito from 'amazon-cognito-identity-js';`

Everything appears to bundle correctly but in the browser I am getting the following error: **ReferenceError: require is not defined**

Error is here:

```
eval("var AWS = require('./core');\n\n// Load browser API loader\nAWS.apiLoader = function(svc, version) {\n  return AWS.apiLoader.services[svc][version];\n};\n\n/**\n * @api private\n */\nAWS.apiLoader.services = {};\n\n// Load the DOMParser XML parser\nAWS.XML.Parser = require('./xml/browser_parser');\n\n// Load the XHR HttpClient\nrequire('./http/xhr');\n\nif (typeof window !== 'undefined') window.AWS = AWS;\nif (typeof module !== 'undefined') module.exports = AWS;\nif (typeof self !== 'undefined') self.AWS = AWS;\n\n\n/*****************\n ** WEBPACK FOOTER\n ** ./~/aws-sdk/lib/browser.js\n ** module id = 389\n ** module chunks = 1\n **/\n//# sourceURL=webpack:///./~/aws-sdk/lib/browser.js?");
```

**Comment by simonbuchan** [comment]
I'll take a look when I get home, but it looks like the alias for aws-sdk
to load the dist bundle isn't kicking in? The eval is a bit suspect too,
webpack shouldn't be adding anything like that.

**Comment by simonbuchan** [comment]
Blarg dumb typo, should be something like resolve.alias.aws-sdk$ - I.e it's missing the alias map.
I'll put up a pr showing webpack usage in the readme when I'm not on a phone; I'm using something a little different right now

**Comment by simonbuchan** [comment]
@jeffski I updated the description w/ the fixed resolve.alias; this seems to work for me with a fresh project.

I noticed I didn't spec `aws-sdk` as a peer dep, not sure what the manners on that are when a custom build is reccommeded, maybe recommend `npm install --save ./my-custom-aws-sdk` where that contains a `package.json` with `"name": "aws-sdk"`...

**Comment by jeffski** [comment]
Thanks @simonbuchan. It's working now with the alias. Also I didn't have the exports-loader installed so that was initially giving me errors too. I'll want to move to a custom aws-sdk build eventually but will cross that bridge when I come to it I guess.

Great job putting this together BTW. I spent the last couple of nights trying to cobble something together so perfect timing as well.

**Comment by itrestian** [comment]
Thanks @simonbuchan! If possible, can you update the readme as well?

**Comment by simonbuchan** [comment]
@itrestian sure, I'd like to figure out if there's a decent way to deal with `aws-sdk` and possibly mention other bundler options like rollup, but I can get this example added at least.

As the updated example comment mentions I'm currently using a slightly more fiddly build which means you don't need a custom `aws-sdk` build, but I'd like to see what other options there are, eg `import S3 from 'aws-sdk!s3'`.

**Comment by simonbuchan** [comment]
@itrestian probably should also update the examples to show the difference with using the SDK as a module - that is, you don't need to get the exports off of `AWSCognito.CognitoIdentityServiceProvider`? That should probably wait until this is published on npm though.

``` patch
-var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
+var cognito = require('amazon-cognito-identity-js');
+var userPool = new cognito.CognitoUserPool(poolData);
```

**Comment by sarah-pixvana** [comment]
@jeffski what exactly did you need to add to your alias mapping to get rid of the require error? I am experiencing the same error although I have my alias mapped as below in my webpack.config file. 

```
var webpack = require('webpack');
const AWS_SDK_MAIN = 'aws-sdk/dist/aws-sdk.min';
const AWS_COGNITO_SDK_MAIN = require.resolve('amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js');


module.exports = {
  resolve: {
    extensions: ['', '.js', '.jsx'],
        alias: {
      'aws-sdk$': AWS_COGNITO_SDK_MAIN
    }
  },
  module: {
    loaders: [
    {test: require.resolve(AWS_COGNITO_SDK_MAIN), loader: 'exports?AWSCognito' },
    {test: require.resolve(AWS_SDK_MAIN),loader: 'exports?AWS',}
    ],
    noParse:  [
      /aws\-sdk/,
      /amazon/,
      /aws-cognito-identity-js/,
      /aws-cognito-sdk/
    ],
    preLoaders: [
      {
        test: /\.min\.js$/,
        loader: 'source-map'
      }
    ],
  },
  plugins: [
    new webpack.ProvidePlugin({
      AWS: AWS_SDK_MAIN,
      AWSCognito: AWS_COGNITO_SDK_MAIN,
    }),
  ]
};
```

**Comment by simonbuchan** [comment]
@sarah-pixvana It looks like you are over-using `noParse`, you should just need `/aws-sdk/` and/or `/aws-cognito-sdk/` depending on which you are loading. `noParse` basically says that "this file doesn't require any other modules and can be wrapped as is", which is _not_ true of the UMD bundle when used as a module (it requires `aws-sdk`, `sjcl` and `jsbn`).

Otherwise:
- you shold not need both aws-sdk and aws-cognito-sdk, the former is a superset of the latter, so you can just use it to shave a few hundred kB off your bundle (that is, only require `aws-sdk` point it's alias at `AWS_SDK_MAIN` if you are using other AWS services)
- you shouldn't need the `ProvidePlugin` if you update your code to require `aws-sdk` explicitly: all it does is insert imports for code using those variables.

**Comment by sarah-pixvana** [comment]
Thanks @simonbuchan I have taken your advice to only use aws-sdk and point its alias at `AWS_SDK_MAIN`and updated my `noParse`. That got rid of the require error. 

Now how would I import the AWSCognito module from the regular aws-sdk? 

Here are a couple things I have tried but result in errors:

`
import AWSCognito from 'aws-sdk';` returns an empty AWSCognito object

`import  'amazon-cognito-identity-js';` returns error: `Cannot set property 'AuthenticationDetails' of undefined`

**Comment by simonbuchan** [comment]
`import AWSCognito from 'aws-sdk'` should work if the `exports-loader` is set up right (ie `exports?AWS` for `AWS_SDK_MAIN`)?

**Comment by simonbuchan** [comment]
I could add a better runtime error for `amazon-cognito-identity-js` for when `aws-sdk` is not set up right...

**Comment by sarah-pixvana** [comment]
Ok my bad, my exports was not set up properly. Now AWSCognito is importing properly. Yay. 

I do think better runtime errors would rock :) 

thanks for the help!

**Pull request merged**
